export const AUTH_LOGIN_EMAIL_REQUEST = "@auth/AUTH_LOGIN_EMAIL_REQUEST";

export const AUTH_LOGIN_SUCCESS = "@auth/AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "@auth/AUTH_LOGIN_FAILURE";

export const AUTH_REGISTER_REQUEST = "@auth/AUTH_REGISTER_REQUEST";
export const AUTH_REGISTER_SUCCESS = "@auth/AUTH_REGISTER_SUCCESS";
export const AUTH_REGISTER_FAILURE = "@auth/AUTH_REGISTER_FAILURE";

export const AUTH_LOGOUT_REQUEST = "@auth/AUTH_LOGOUT_REQUEST";
export const AUTH_LOGOUT_SUCCESS = "@auth/AUTH_LOGOUT_SUCCESS";
export const AUTH_LOGOUT_FAILURE = "@auth/AUTH_LOGOUT_FAILURE";
